server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PortalSekolah
    username: root
    password: jikolpu031198
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 8407312fab6eb7
    password: 323501392134c9

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          
validationLink: http://localhost:8080/user/confirm?token=

